### ISSUE TITLE
Own theme Dark and Clear

### ISSUE THREAD

**Issue by kadmef** [rlazom/easy_dynamic_theme#4]
wish evolution in Flutter/Dart:
switch dynamically via my own two pre-defined themes ThemeDark and ThemeClear
 
Here is my own Dark Theme “ThemeDark” in AndroidStudio with Java (Not dart)
<style name="ThemeDark" parent="Theme.AppCompat.DayNight.NoActionBar">
<item name="colorPrimaryDark">@color/colorPrimaryDarkTop</item>      // 
<item name="colorPrimary">@color/colorPrimaryDarkLow</item>
<item name="colorAccent">@color/colorAccentDark</item>
<item name="colorControlNormal">@color/colorControlNormalDark</item>
<item name="colorControlActivated">@color/colorControlActivatedDark</item>
<item name="colorControlHighlight">@color/colorControlHighlightDark</item>
<item name="background">@color/colorPrimaryDarkMinus1</item>
<item name="textColor">@color/colorWhite</item>
<item name="android:radioButtonStyle">@style/ThemeDarkRadioButton</item>
</style>
<style name="ThemeClear" parent="Theme.AppCompat.Light.NoActionBar">
. . .
</style>
Thank you!

**Comment by rlazom** [comment]
I think the best option for you is to follow the "[How to use predefined Themes](https://github.com/rlazom/easy_dynamic_theme#how-to-use-predefined-themes)" in the Readme file.

With that approach I think you can achieve what you want

Tell me if you need any extra help
Cheers

**Comment by rlazom** [comment]
@kadmef the comment above solves your question?
