### ISSUE TITLE
How to force the "light" mode?

### ISSUE THREAD

**Issue by yom-ko** [rlazom/easy_dynamic_theme#8]
@rlazom Hello

First, thanks for the package! It works pretty well for my app.

One question though – how to force the "light" mode in a dropdown with three options (system, light, and dark)? Based on this order `dynamic -> light -> dark -> dynamic ->`, it turns out that the only reliable way to do it is to call the `changeTheme` method twice, one after another, eg:
```
EasyDynamicTheme.of(context).changeTheme(dynamic: true);
EasyDynamicTheme.of(context).changeTheme();
``` 
It does the trick but feels a bit awkward. Am I right that this is the only available solution for now?

**Comment by rlazom** [comment]
First, thanks for your comments, and sorry for the delay in the answer...

Now, According to the plugin documentation:

```
How to change the ThemeMode in your app 
You can use the function changeTheme from anywhere in your app.

This function have two optional parameters: dynamic and dark. If the value of dynamic is true, it takes precedence over dark.
```

So, you could be able to achieve what you want with:
```
// Theme Mode Light
EasyDynamicTheme.of(context).changeTheme(dark: false)

// Theme Mode dark
EasyDynamicTheme.of(context).changeTheme(dark: true)
```

**Comment by yom-ko** [comment]
Hi, thanks! For some reason, I was sure that the `dark` param was `false` by default and could only be set to `true`. Worse than that, I missed the doc popup in my IDE over and over, as if there was a blind spot. My bad.

**Comment by rlazom** [comment]
Glad to help 😉

Can I close the issue if it's solved then?

**Comment by yom-ko** [comment]
Sure!
